[package]
name = "i3-switcher-x11"
version = "0.1.0"
edition = "2021"
build = "build.rs" 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.8.0"
i3ipc = "0.10.1"
x11 = "2.21.0"
